/* SPDX-License-Identifier: Apache-2.0 */

/* Generated by tools/api.py. */
#ifndef CRUST0_ABI_H
#define CRUST0_ABI_H

#define CRUST_ABI_DIGEST "fad7e198d278cf13d42bde4bf98ccf35c63c34c441565c6669b056c300127a1a"
/* clang-format off */
#define CRUST_ABI_NAMES {"CRUST_ABI_crust0", "CRUST_ABI_crust0_host", "CRUST_ABI_crust0_x64", "CRUST_ABI_crust0_stage", "CRUST_ABI_crust0_eval", "CRUST_ABI_crust0_run"}
/* clang-format on */
/* Use once in a native library translation unit. */
#define CRUST_ABI_EXPORT const char *const CRUST_ABI_crust0 = CRUST_ABI_DIGEST

#endif
