#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the frontend translation unit from its maintained C sources."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ("src/core.c", "src/read.c", "src/check.c")
OUTPUT = ROOT / "crust0_amalg.c"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    parts = [
        "/* SPDX-License-Identifier: Apache-2.0 */\n\n",
        "/* Generated by tools/amalgamate.py. Edit the source files instead. */\n",
        "#define CRUST_AMALGAMATED\n",
    ]
    for source in SOURCES:
        parts.append(f'\n/* {source} */\n#line 1 "{source}"\n')
        parts.append((ROOT / source).read_text())
    generated = "".join(parts)
    if OUTPUT.exists() and OUTPUT.read_text() == generated:
        return 0
    if args.check:
        print("crust0_amalg.c is stale; run python3 tools/amalgamate.py")
        return 1
    OUTPUT.write_text(generated)
    print("updated crust0_amalg.c")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
