#!/usr/bin/env python3
"""Publish the RMD0 declarations for the compiler's selected C99 interface."""

import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
C_ONLY = {
    "rmd_run_stage", "rmd_alloc", "rmd_grow_array", "rmd_copy_string",
    "rmd_intern", "rmd_fail", "rmd_map_set", "rmd_resolve_type", "rmd_pointer_type",
    "rmd_x64_reserve", "rmd_x64_prepare_function", "rmd_x64_output",
    "rmd_x64_emit_function", "rmd_x64_emit_expression", "rmd_x64_emit_place",
    "rmd_x64_emit_statement", "rmd_x64_emit_constant", "rmd_x64_emit_constant_value",
}
SCALARS = {
    "void": "unit", "bool": "bool", "char": "u8", "unsigned char": "u8",
    "int32_t": "i32", "uint32_t": "u32", "uint64_t": "u64", "size_t": "usize",
    "uintptr_t": "usize", "unsigned": "u32",
}
OPAQUE = {"void", "FILE", "RmdArenaBlock", "RmdFailureFrame", "RmdEval", "RmdRunState"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    enums = {}
    headers = {}
    for stem in ("rmd0", "rmd0_host", "rmd0_x64", "rmd0_stage", "rmd0_eval", "rmd0_run"):
        source = (ROOT / "include" / f"{stem}.h").read_text()
        source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
        source = re.sub(r"^#.*$", "", source, flags=re.M)
        headers[stem] = source
        for body, name in re.findall(r"typedef enum\s*\{(.*?)\}\s*(\w+)\s*;", source, re.S):
            enums[name] = [value.strip() for value in body.split(",") if value.strip()]
            if any(not re.fullmatch(r"\w+", value) for value in enums[name]):
                raise ValueError(f"unsupported explicit enum value in {name}")

    def ctype(text):
        text = re.sub(r"\bconst\b", "", text)
        pointers = text.count("*")
        base = " ".join(text.replace("*", " ").split())
        if pointers and base in OPAQUE:
            base = "u8"
        elif base in SCALARS:
            base = SCALARS[base]
        elif base in enums:
            base = "u32"
        elif not re.fullmatch(r"Rmd\w+", base):
            raise ValueError(f"unsupported interface type: {text}")
        return "*" * pointers + base

    def declaration(text):
        text = " ".join(text.split())
        callback = re.fullmatch(r"(.+?)\(\*(\w+)\)\((.*)\)", text)
        if callback:
            result, name, arguments = callback.groups()
            types = [declaration(arg)[1] for arg in arguments.split(",")] if arguments != "void" else []
            return name, f"fn({', '.join(types)}) -> {ctype(result)}"
        ordinary = re.fullmatch(r"(.+?[\s*])(\w+)(?:\[([^]]+)\])?", text)
        if not ordinary:
            raise ValueError(f"unsupported interface declaration: {text}")
        result, name, count = ordinary.groups()
        result = ctype(result)
        if count:
            if count == "RMD_T_UNIT + 1":
                count = str(enums["RmdTypeKind"].index("RMD_T_UNIT") + 1)
            if not count.isdecimal():
                raise ValueError(f"unsupported interface array: {text}")
            result = f"[{result}; {count}]"
        return name, result

    for stem, source in headers.items():
        lines = ["// Generated by tools/api.py. The layouts apply to this package version.", ""]
        for body, name in re.findall(r"typedef enum\s*\{(.*?)\}\s*(\w+)\s*;", source, re.S):
            for index, value in enumerate(enums[name]):
                lines.append(f"const {value}: u32 = {index}u32;")
            lines.append("")
        record_pattern = r"(?:typedef\s+)?struct\s*(\w+)?\s*\{(.*?)\}\s*(\w+)?\s*;"
        for before, body, after in re.findall(record_pattern, source, re.S):
            name = after or before
            if name in OPAQUE:
                continue
            lines.append(f"record {name} {{")
            for field in body.split(";"):
                if field.strip():
                    field_name, field_type = declaration(field)
                    lines.append(f"    {field_name}: {field_type};")
            lines.extend(["}", ""])
        remaining = re.sub(record_pattern, "", source, flags=re.S)
        remaining = re.sub(r"typedef enum\s*\{.*?\}\s*\w+\s*;", "", remaining, flags=re.S)
        remaining = re.sub(r"typedef struct \w+ \w+\s*;", "", remaining)
        remaining = re.sub(r"extern const RmdX64Ops rmd_x64_default_ops\s*;", "", remaining)
        for prototype in remaining.split(";"):
            prototype = " ".join(prototype.split())
            if not prototype:
                continue
            match = re.fullmatch(r"(.+?[\s*])(\w+)\((.*)\)", prototype)
            if not match:
                raise ValueError(f"unsupported interface prototype: {prototype}")
            result, name, arguments = match.groups()
            if name in C_ONLY:
                continue
            params = [declaration(arg) for arg in arguments.split(",")] if arguments != "void" else []
            rendered = ", ".join(f"{param}: {kind}" for param, kind in params)
            lines.append(f'extern fn {name}({rendered}) -> {ctype(result)} = "{name}";')
        output = "\n".join(lines).rstrip() + "\n"
        path = ROOT / "api" / f"{stem}.rmd"
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(f"API declarations differ: {path.relative_to(ROOT)}; run tools/api.py")
        else:
            path.write_text(output)


if __name__ == "__main__":
    main()
