#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Publish the CRUST0 declarations for the compiler's selected C99 interface."""

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
C_ONLY = {
    "crust_run_stage",
    "crust_alloc",
    "crust_grow_array",
    "crust_copy_string",
    "crust_intern",
    "crust_fail",
    "crust_map_set",
    "crust_resolve_type",
    "crust_pointer_type",
    "crust_type_equal",
    "crust_x64_reserve",
    "crust_x64_prepare_function",
    "crust_x64_output",
    "crust_x64_emit_function",
    "crust_x64_emit_expression",
    "crust_x64_emit_place",
    "crust_x64_emit_statement",
    "crust_x64_emit_constant",
    "crust_x64_emit_constant_value",
}
SCALARS = {
    "void": "unit",
    "bool": "bool",
    "char": "u8",
    "unsigned char": "u8",
    "int32_t": "i32",
    "uint32_t": "u32",
    "uint64_t": "u64",
    "size_t": "usize",
    "uintptr_t": "usize",
    "unsigned": "u32",
}
OPAQUE = {"void", "FILE", "CrustArenaBlock", "CrustFailureFrame", "CrustEval", "CrustRunState"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    enums = {}
    headers = {}
    for stem in (
        "crust0",
        "crust0_host",
        "crust0_x64",
        "crust0_stage",
        "crust0_eval",
        "crust0_run",
    ):
        source = (ROOT / "include" / f"{stem}.h").read_text()
        source = source.replace("\\\n", "")
        source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
        source = re.sub(r"^#.*$", "", source, flags=re.M)
        headers[stem] = source
        for body, name in re.findall(r"typedef enum\s*\{(.*?)\}\s*(\w+)\s*;", source, re.S):
            enums[name] = [value.strip() for value in body.split(",") if value.strip()]
            if any(not re.fullmatch(r"\w+", value) for value in enums[name]):
                raise ValueError(f"unsupported explicit enum value in {name}")

    def ctype(text):
        text = re.sub(r"\bconst\b", "", text)
        pointers = text.count("*")
        base = " ".join(text.replace("*", " ").split())
        if pointers and base in OPAQUE:
            base = "u8"
        elif base in SCALARS:
            base = SCALARS[base]
        elif base in enums:
            base = "u32"
        elif not re.fullmatch(r"Crust\w+", base):
            raise ValueError(f"unsupported interface type: {text}")
        return "*" * pointers + base

    def declaration(text):
        text = " ".join(text.split())
        callback = re.fullmatch(r"(.+?)\(\*(\w+)\)\((.*)\)", text)
        if callback:
            result, name, arguments = callback.groups()
            types = (
                [declaration(arg)[1] for arg in arguments.split(",")] if arguments != "void" else []
            )
            return name, f"fn({', '.join(types)}) -> {ctype(result)}"
        ordinary = re.fullmatch(r"(.+?[\s*])(\w+)(?:\[([^]]+)\])?", text)
        if not ordinary:
            raise ValueError(f"unsupported interface declaration: {text}")
        result, name, count = ordinary.groups()
        result = ctype(result)
        if count:
            if count == "CRUST_T_UNIT + 1":
                count = str(enums["CrustTypeKind"].index("CRUST_T_UNIT") + 1)
            if not count.isdecimal():
                raise ValueError(f"unsupported interface array: {text}")
            result = f"[{result}; {count}]"
        return name, result

    for stem, source in headers.items():
        lines = [
            "// SPDX-License-Identifier: Apache-2.0",
            "",
            "// Generated by tools/api.py. The layouts apply to this package version.",
            "",
        ]
        for _body, name in re.findall(r"typedef enum\s*\{(.*?)\}\s*(\w+)\s*;", source, re.S):
            for index, value in enumerate(enums[name]):
                lines.append(f"const {value}: u32 = {index}u32;")
            lines.append("")
        record_pattern = r"(?:typedef\s+)?struct\s*(\w+)?\s*\{(.*?)\}\s*(\w+)?\s*;"
        for before, body, after in re.findall(record_pattern, source, re.S):
            name = after or before
            if name in OPAQUE:
                continue
            lines.append(f"record {name} {{")
            for field in body.split(";"):
                if field.strip():
                    field_name, field_type = declaration(field)
                    lines.append(f"    {field_name}: {field_type};")
            lines.extend(["}", ""])
        remaining = re.sub(record_pattern, "", source, flags=re.S)
        remaining = re.sub(r"typedef enum\s*\{.*?\}\s*\w+\s*;", "", remaining, flags=re.S)
        remaining = re.sub(r"typedef struct \w+ \w+\s*;", "", remaining)
        remaining = re.sub(r"extern const CrustX64Ops crust_x64_default_ops\s*;", "", remaining)
        for prototype in remaining.split(";"):
            prototype = " ".join(prototype.split())
            if not prototype:
                continue
            match = re.fullmatch(r"(.+?[\s*])(\w+)\((.*)\)", prototype)
            if not match:
                raise ValueError(f"unsupported interface prototype: {prototype}")
            result, name, arguments = match.groups()
            if name in C_ONLY:
                continue
            params = (
                [declaration(arg) for arg in arguments.split(",")] if arguments != "void" else []
            )
            rendered = ", ".join(f"{param}: {kind}" for param, kind in params)
            lines.append(f'extern fn {name}({rendered}) -> {ctype(result)} = "{name}";')
        output = "\n".join(lines).rstrip() + "\n"
        path = ROOT / "api" / f"{stem}.crs"
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(
                    f"API declarations differ: {path.relative_to(ROOT)}; run tools/api.py"
                )
        else:
            path.write_text(output)


if __name__ == "__main__":
    main()
